### ISSUE TITLE
there is a type in the applicaiont

### ISSUE THREAD

**Issue by pluralsight-demo-oscar** [pluralsight-demo-oscar-org/turbo-computing-machine#1]
I found a typo on the second screen of the app, you need to fix this now #

**Comment by pluralsight-demo-oscar** [comment]
I looked at this and it's spelled correctly. Where did you see it

**Comment by oscarlagatta** [comment]
Checked and there's no spelling error

**Comment by oscarlagatta** [comment]
I'm replying from my email so it's okay

**Comment by oscarlagatta** [comment]
it's gone
